debug: &debug false

db:
    master:
        server: maxbicotest.database.windows.net
        database: TestSPList
        username: TestTask
        password: TestDev20191
        driver: ODBC Driver 17 for SQL Server
