debug: &debug true
#host: localhost

#api:
#    host: localhost
#    port: 8000
#
#redis:
#    host: localhost
#    port: 6379
#    db:
#        cache: 0

db:
    master:
        server: maxbicotest.database.windows.net
        database: TestSPList
        username: TestTask
        password: TestDev20191
        driver: ODBC Driver 17 for SQL Server

#db_autocommit: true
#
#logging:
#    level: DEBUG
#    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
#    filename: log/errors.log
#    maxBytes: 1024
#    backupCount: 3
